"""
Build the house-price linear regression notebook (notebooks/house_price_linear_regression.ipynb).

The notebook is written with nbformat so that every cell is explicit and the file can be
regenerated/reviewed as plain Python here.
"""
from __future__ import annotations

import nbformat as nbf

nb = nbf.v4.new_notebook()
cells: list = []


def md(text: str) -> None:
    cells.append(nbf.v4.new_markdown_cell(text.strip("\n")))


def code(text: str) -> None:
    cells.append(nbf.v4.new_code_cell(text.strip("\n")))


# ======================================================================
md(
    """
# Predicting House Prices with Linear Regression

**Objective.** Build and evaluate a linear regression model that predicts house prices from
features such as **area, location, number of rooms, and age** — covering the full pipeline from
data cleaning through to model interpretation.

**Dataset.** `data/house_prices.csv` — an Ames-Housing-style dataset (2,945 rows x 9 columns)
generated by `data/generate_dataset.py`. It mirrors the structure of the Kaggle
*"House Prices: Advanced Regression Techniques"* (Ames) dataset, including real missing values
and a categorical `location` column, so every cleaning step below is genuine rather than cosmetic.

**Tech stack:** Python, pandas, scikit-learn, matplotlib, seaborn.

---

### Pipeline checklist
1. Load & EDA (nulls, descriptive stats, target distribution)
2. Feature-selection discussion
3. Missing-value handling + One-Hot Encoding
4. Correlation heatmap
5. 80/20 train/test split
6. Train Linear Regression
7. Evaluate: MSE, RMSE, R²
8. Actual vs predicted scatter
9. Residual plot
10. Coefficient analysis
11. Bonus: Ridge / Lasso comparison
"""
)

md("## 0. Imports & configuration\nPin a random seed so every result is reproducible.")

code(
    """
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

sns.set_theme(style="whitegrid", context="notebook")
plt.rcParams["figure.dpi"] = 110
pd.set_option("display.float_format", lambda v: f"{v:,.2f}")

RANDOM_STATE = 42
print("numpy", np.__version__, "| pandas", pd.__version__, "| seaborn", sns.__version__)
"""
)

# ======================================================================
md(
    """
## 1. Load the dataset and exploratory data analysis (EDA)

We first load the data and check its shape, data types, and how many values are missing.
`price` is our **target**; everything else is a candidate **feature**.
"""
)

code(
    """
df = pd.read_csv("../data/house_prices.csv")
print("Shape:", df.shape)
print("\\nData types:\\n", df.dtypes)
df.head()
"""
)

md("### 1.1 Null-value check\nCount and percentage of missing values per column.")

code(
    """
null_counts = df.isnull().sum()
null_pct = (null_counts / len(df) * 100).round(2)
null_report = pd.DataFrame({"missing": null_counts, "pct": null_pct})
null_report = null_report[null_report["missing"] > 0].sort_values("missing", ascending=False)
print("Columns with missing values:\\n", null_report.to_string())
print("\\nTotal missing cells:", int(null_counts.sum()))
"""
)

md("### 1.2 Descriptive statistics\nSummary stats for the numeric columns, plus the categorical `location`.")

code(
    """
df.describe().T
"""
)

code(
    """
print("Location categories and counts:\\n")
print(df["location"].value_counts().to_string())
# Non-numeric columns (works across pandas 2 and 3, where text columns may be 'object' or 'str').
cat_cols = [c for c in df.columns if not pd.api.types.is_numeric_dtype(df[c])]
print("\\nCategorical columns:", cat_cols)
"""
)

md(
    """
Notice the **scale mismatch**: `price` is in the hundreds of thousands while `rooms`/`garage`
are single digits. That's fine for plain OLS, but it's why we standardise features for the
regularised models later (so that the penalty is applied fairly across coefficients).

### 1.3 Distribution of the target variable (`price`)

The target distribution matters for linear regression: a strongly skewed target often produces
heteroscedastic residuals (a fan shape), which we will check again on the residual plot.
"""
)

code(
    """
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))

sns.histplot(df["price"], bins=45, kde=True, ax=axes[0], color="#2a6f97")
axes[0].set_title("Distribution of house price")
axes[0].set_xlabel("Price ($)")

sns.boxplot(x=df["price"], ax=axes[1], color="#61a5c2")
axes[1].set_title("Boxplot of price (outlier check)")
axes[1].set_xlabel("Price ($)")

plt.tight_layout()
plt.savefig("../figures/01_price_distribution.png", bbox_inches="tight")
plt.show()

print(f"Skewness: {df['price'].skew():.3f}")
print(f"Kurtosis: {df['price'].kurtosis():.3f}")
"""
)

md(
    """
**Reading the plot.** The price distribution is mildly right-skewed with a small number of
high-end homes. This is normal for house prices. We keep the outliers for now (they are
plausible real prices, e.g. waterfront properties) but we note that a log-transform of the
target is a common refinement — we touch on it in the conclusions.
"""
)

# ======================================================================
md(
    """
## 2. Feature selection discussion

Before modelling, we reason about which features are likely to predict `price`. In linear
regression, "good" predictors are those (a) plausibly related to price, (b) not wildly
redundant with each other (multicollinearity inflates coefficient variance), and (c) available
at prediction time.

| Feature | Type | Expected effect on price | Reasoning |
|---|---|
| `area` | numeric | **Strong +** | Living area is the single most consistent driver of home value; larger homes cost more. |
| `rooms` | numeric | **Moderate +** | More rooms generally means more usable space. But it's *partly redundant with `area`* — a big open-plan home has few rooms but high value, so the two are correlated. |
| `bathrooms` | numeric | **Moderate +** | Bathrooms are an expensive, value-adding feature and are not fully captured by room count. |
| `garage` | numeric | **Weak/Moderate +** | Off-street parking adds value, especially in dense/urban areas. |
| `age` | numeric | **Negative** | Older homes (all else equal) typically sell for less, though historic/renovated ones can buck the trend. Non-linear in reality. |
| `quality` | numeric | **Strong +** | Overall quality rating is one of the best predictors in the real Ames dataset. |
| `renovated` | binary | **Weak +** | A recently renovated home commands a modest premium. |
| `location` | categorical | **Strong (mixed sign)** | Location drives price more than almost anything. Waterfront commands a big premium; Rural trades at a discount. Must be **One-Hot Encoded**. Need to be careful with a category with very few observations (near-constant dummy). |

**Deliberately excluded / considered carefully**
- `price` itself is the target — obviously not a feature.
- We have no `id`/leakage columns here. In the real Kaggle data we would drop `Id` and any
  column that is only known *after* the sale.

**What we will NOT do:** remove correlated features blindly. Instead we keep them, watch the
correlation heatmap and the coefficient table, and mention multicollinearity where relevant.
"""
)

# ======================================================================
md(
    """
## 3. Clean the data: missing values + One-Hot Encoding

### 3.1 Handle duplicates

Synthetic data can contain accidental duplicate rows; drop them so they don't inflate the
weight of a single observation.
"""
)

code(
    """
before = len(df)
df = df.drop_duplicates().reset_index(drop=True)
print(f"Dropped {before - len(df)} duplicate rows. New shape: {df.shape}")
"""
)

md(
    """
### 3.2 Impute missing values

Strategy per column:

- `area`, `bathrooms`, `age` — **median** imputation. Median is robust to skew and outliers.
  (We could condition on `rooms`/`location`, but for a first pass a global median is a
  reasonable, defensible default.)
- `garage` — **median** imputation. Alternatively `0` is arguable for garage count, but the
  median keeps the column's central tendency intact.

We impute with statistics computed on the full data here for clarity; in a strict deployment
you would fit the imputer on the **training set only** (see the note after the split).
"""
)

code(
    """
num_cols_with_na = ["area", "bathrooms", "garage", "age"]
median_fill = df[num_cols_with_na].median()
print("Medians used for imputation:\\n", median_fill.to_string())

df[num_cols_with_na] = df[num_cols_with_na].fillna(median_fill)

print("\\nRemaining missing values:", int(df.isnull().sum().sum()))

# Defence in depth: assert the frame handed to the model has no NaNs left.
assert df.isnull().sum().sum() == 0, "Unexpected missing values remain"
print("No missing values remain - safe to model.")
"""
)

md(
    """
> **Best practice note:** strictly, imputation statistics should be learned on the training
> split and applied to the test split to avoid leakage. Here we show the simple version for
> readability; the box below the train/test split demonstrates the leakage-safe pattern.
> Because we use a robust global median over ~3,000 rows, the practical difference is tiny,
> but the correct habit matters in production.

### 3.3 One-Hot Encode `location`

`location` is nominal (no natural order), so we create binary dummy columns.
We use `drop_first=True` to avoid the **dummy-variable trap** (perfect multicollinearity),
leaving a reference category that every coefficient is interpreted relative to.
"""
)

code(
    """
df_encoded = pd.get_dummies(df, columns=["location"], drop_first=True, dtype=int)

# Clean up any spaces in the generated column names.
df_encoded.columns = [c.replace(" ", "_") for c in df_encoded.columns]

print("Encoded shape:", df_encoded.shape)
print("\\nColumns after encoding:\\n", list(df_encoded.columns))
df_encoded.head()
"""
)

md(
    """
The reference category is whichever category was dropped first (alphabetically, that is
`Downtown`). Every `location_*` coefficient is therefore read as *"the price difference versus
Downtown, holding other features constant."*
"""
)

# ======================================================================
md(
    """
## 4. Correlation heatmap

Pearson correlation between every numeric/encoded feature and the target. This validates (or
challenges) our feature-selection reasoning in section 2.
"""
)

code(
    """
corr = df_encoded.corr(numeric_only=True)

fig, ax = plt.subplots(figsize=(10, 8))
sns.heatmap(
    corr,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    square=True,
    linewidths=0.5,
    cbar_kws={"shrink": 0.8},
    ax=ax,
)
ax.set_title("Correlation heatmap (encoded features)")
plt.tight_layout()
plt.savefig("../figures/02_correlation_heatmap.png", bbox_inches="tight")
plt.show()

print("Correlation with price (sorted):\\n")
print(corr["price"].drop("price").sort_values(ascending=False).to_string())
"""
)

md(
    """
**Interpretation.** The heatmap lets us spot two things:

1. **Signals** — the features most correlated with `price` (large positive/negative values in
   the `price` row/column). We expect `area` and `quality` near the top.
2. **Multicollinearity** — pairs of features that are strongly correlated with *each other*.
   `area` and `rooms` typically correlate, which we flagged in section 2. High pairwise
   correlation means their individual coefficients can be unstable / hard to interpret, which
   is exactly the problem Ridge/Lasso (°bonus section) are designed to tame.
"""
)

# ======================================================================
md(
    """
## 5. Train / test split (80 / 20)

We hold out 20% of the data to estimate out-of-sample performance. `random_state` makes the
split reproducible.
"""
)

code(
    """
X = df_encoded.drop(columns="price")
y = df_encoded["price"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=RANDOM_STATE
)

print("Train:", X_train.shape, " Test:", X_test.shape)
print(f"Train price mean: ${y_train.mean():,.0f}   Test price mean: ${y_test.mean():,.0f}")
"""
)

md(
    """
### (Optional) Leakage-safe imputation pattern

For reference, the production-correct way to impute looks like this — compute the statistic on
the **training** data only, then apply it to both splits:

```python
# train_median = X_train[["area", "bathrooms", "garage", "age"]].median()
# X_train[num_cols_with_na] = X_train[num_cols_with_na].fillna(train_median)
# X_test[num_cols_with_na]  = X_test[num_cols_with_na].fillna(train_median)
```
"""
)

# ======================================================================
md(
    """
## 6. Train a Linear Regression model

scikit-learn's [`LinearRegression`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)
fits coefficients by minimising the residual sum of squares (ordinary least squares).
"""
)

code(
    """
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

train_pred = lin_reg.predict(X_train)
test_pred = lin_reg.predict(X_test)

print("Model fitted.")
print(f"Intercept: {lin_reg.intercept_:,.2f}")
"""
)

# ======================================================================
md(
    """
## 7. Evaluate: MSE, RMSE, and R²

- **MSE** — mean squared error, in dollars² (hard to read, but the basis of the loss).
- **RMSE** — square root of MSE, back in **dollars**, so it reads as "typical error size".
- **R²** — fraction of price variance explained (1.0 = perfect, 0 = no better than the mean).

We report all three on **both** train and test to detect over/underfitting.
"""
)

code(
    """
def evaluate(name, y_true, y_pred):
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    print(f"{name:<8} | MSE: {mse:>18,.0f} | RMSE: {rmse:>12,.0f} | MAE: {mae:>12,.0f} | R2: {r2:.4f}")
    return {"mse": mse, "rmse": rmse, "mae": mae, "r2": r2}

train_metrics = evaluate("Train", y_train, train_pred)
print("-" * 92)
test_metrics = evaluate("Test", y_test, test_pred)
"""
)

code(
    """
# The same numbers in a tidy table, and RMSE as a % of the average house price.
metrics_df = pd.DataFrame({"Train": train_metrics, "Test": test_metrics}).T
metrics_df["rmse_pct_of_mean_price"] = (metrics_df["rmse"] / y.mean() * 100).round(2)

# Present dollars as integers and R2 with 4 decimals.
print(metrics_df.to_string(
    formatters={
        "mse": "{:,.0f}".format,
        "rmse": "{:,.0f}".format,
        "mae": "{:,.0f}".format,
        "r2": "{:.4f}".format,
        "rmse_pct_of_mean_price": "{:.2f}%".format,
    }
))
"""
)

md(
    """
**Reading the scores.**

- Train and test R² being **close together** means the model is not overfitting.
- RMSE interpreted as a percentage of the mean price gives an intuitive "typical % error".
- If test R² were far below train R², we'd suspect overfitting; if both were low, underfitting.

Remember R² is relative: a modest R² can still be useful, and for noisy real estate data an
R² in the 0.6–0.85 range is a solid linear baseline.
"""
)

# ======================================================================
md(
    """
## 8. Actual vs. predicted prices

Each point is one held-out house: x = true price, y = predicted price. A perfect model puts
every point on the red 45° diagonal.
"""
)

code(
    """
fig, ax = plt.subplots(figsize=(7.5, 7))

ax.scatter(y_test, test_pred, alpha=0.45, s=18, color="#2a6f97", edgecolors="none")

lo = min(y_test.min(), test_pred.min())
hi = max(y_test.max(), test_pred.max())
ax.plot([lo, hi], [lo, hi], "r--", linewidth=2, label="Perfect prediction")

ax.set_xlabel("Actual price ($)")
ax.set_ylabel("Predicted price ($)")
ax.set_title(f"Actual vs. Predicted (test set)  —  R² = {test_metrics['r2']:.3f}")
ax.legend(loc="upper left")

plt.tight_layout()
plt.savefig("../figures/03_actual_vs_predicted.png", bbox_inches="tight")
plt.show()
"""
)

md(
    """
**Reading the plot.** Points hugging the diagonal = accurate predictions. Systematic bowing
above/below the line at the extremes would indicate the model underpredicts expensive homes
and overpredicts cheap ones — a common linear-regression limitation with skewed targets.
"""
)

# ======================================================================
md(
    """
## 9. Residual plot

Residuals = actual − predicted. For OLS to be valid we want them to be:

- centred around **zero** (no bias),
- **randomly scattered** with no funnel or curve (constant variance / "homoscedasticity"),
- roughly **normally** distributed.

A funnel shape (residuals fanning out at higher predictions) signals heteroscedasticity.
"""
)

code(
    """
residuals = y_test - test_pred

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

# Residuals vs predicted
axes[0].scatter(test_pred, residuals, alpha=0.45, s=18, color="#c1121f", edgecolors="none")
axes[0].axhline(0, color="black", linestyle="--", linewidth=1.5)
axes[0].set_xlabel("Predicted price ($)")
axes[0].set_ylabel("Residual (actual − predicted) ($)")
axes[0].set_title("Residuals vs. predicted values")

# Residual distribution
sns.histplot(residuals, bins=45, kde=True, ax=axes[1], color="#3a7ca5")
axes[1].axvline(0, color="black", linestyle="--", linewidth=1.5)
axes[1].set_xlabel("Residual ($)")
axes[1].set_title("Distribution of residuals")

plt.tight_layout()
plt.savefig("../figures/04_residuals.png", bbox_inches="tight")
plt.show()

print(f"Residual mean : {residuals.mean():,.2f}")
print(f"Residual std  : {residuals.std():,.2f}")
print(f"Skewness      : {residuals.skew():.3f}")
"""
)

md(
    """
**Reading the plot.** Ideally the left panel shows a shapeless cloud centred on the dashed zero
line (random scatter, constant spread) and the right panel shows an approximately symmetric
bell around zero. Patterns to call out (and they are worth noting honestly if present):

- **Funnel** (spread grows with predicted price) → heteroscedasticity; consider log(target).
- **Curve/bow** → the true relationship is non-linear; add polynomial terms or interactions.
- **Skewed histogram** → non-normal errors; a log target often fixes it.
"""
)

# ======================================================================
md(
    """
## 10. Coefficient analysis

Which features push price up (positive coefficients) and which pull it down (negative)?
Because our features are on different scales, we look at **both** raw coefficients (dollars per
unit) and standardised coefficients (effect per standard deviation, directly comparable).
"""
)

code(
    """
coefs = pd.DataFrame({
    "feature": X.columns,
    "coefficient": lin_reg.coef_,
})

# Standardised coefficients: multiply by the feature's std => change in $ per 1 SD of feature.
coefs["std_coef"] = coefs["coefficient"] * X.std(ddof=0).values
coefs["abs_std_coef"] = coefs["std_coef"].abs()
coefs = coefs.sort_values("std_coef", ascending=False).reset_index(drop=True)

print("Coefficients (sorted by standardised impact):\\n")
print(coefs.to_string(index=False))
"""
)

code(
    """
fig, ax = plt.subplots(figsize=(9, 6))
colors = ["#2a9d8f" if v >= 0 else "#e76f51" for v in coefs["std_coef"]]
ax.barh(coefs["feature"], coefs["std_coef"], color=colors)
ax.axvline(0, color="black", linewidth=1)
ax.set_xlabel("Standardised coefficient  ($ change per 1 SD of feature)")
ax.set_title("Feature impact on price (standardised coefficients)")
ax.invert_yaxis()
plt.tight_layout()
plt.savefig("../figures/05_coefficients.png", bbox_inches="tight")
plt.show()
"""
)

md(
    """
**Interpretation guide.**

- **Largest positive** standardised coefficient = the feature that moves price the most per
  standard deviation. Expect `area` and/or `quality` at the top.
- **Negative** coefficients mean the feature is associated with *lower* price, holding others
  constant. `age` is the usual suspect (older = cheaper).
- **Location dummies** are read relative to the dropped reference category (`Downtown`):
  a large positive `location_Waterfront` means waterfront homes sell above Downtown.
- **Caution:** correlated features share credit. If `area` and `rooms` are correlated, their
  individual coefficients can be smaller or even flip sign versus their raw correlation with
  price. That's not a bug — it's multicollinearity, and it's the motivation for the Ridge/Lasso
  comparison below.
"""
)

# ======================================================================
md(
    """
## 11. Bonus: Linear Regression vs. Ridge & Lasso

Regularised models add a penalty on coefficient size:

- **Ridge (L2)** — shrinks coefficients, handles multicollinearity gracefully, keeps all
  features.
- **Lasso (L1)** — shrinks and can drive coefficients **exactly to zero**, doing automatic
  feature selection.

We standardise features first so the penalty is applied fairly, then compare test R² and RMSE.
"""
)

code(
    """
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

alphas = [0.1, 1.0, 10.0, 100.0, 1000.0]

results = []
for name, estimator in [
    ("Ridge", Ridge),
    ("Lasso", Lasso),
]:
    for alpha in alphas:
        model = estimator(alpha=alpha, random_state=RANDOM_STATE, max_iter=10000)
        model.fit(X_train_scaled, y_train)
        pred = model.predict(X_test_scaled)
        results.append({
            "model": name,
            "alpha": alpha,
            "test_r2": r2_score(y_test, pred),
            "test_rmse": np.sqrt(mean_squared_error(y_test, pred)),
            "n_nonzero_coefs": int(np.sum(np.abs(model.coef_) > 1e-6)),
        })

# Baseline OLS trained on the scaled features for a like-for-like comparison.
ols_scaled = LinearRegression().fit(X_train_scaled, y_train)
ols_pred = ols_scaled.predict(X_test_scaled)
results.append({
    "model": "OLS (scaled)",
    "alpha": np.nan,
    "test_r2": r2_score(y_test, ols_pred),
    "test_rmse": np.sqrt(mean_squared_error(y_test, ols_pred)),
    "n_nonzero_coefs": int(np.sum(np.abs(ols_scaled.coef_) > 1e-6)),
})

results_df = pd.DataFrame(results).sort_values("test_r2", ascending=False).reset_index(drop=True)
print(results_df.to_string(
    formatters={
        "alpha": lambda v: "-" if pd.isna(v) else f"{v:g}",
        "test_r2": "{:.4f}".format,
        "test_rmse": "{:,.0f}".format,
    }
))
"""
)

code(
    """
fig, ax = plt.subplots(figsize=(9, 5))
for name in ["Ridge", "Lasso"]:
    subset = results_df[results_df["model"] == name].sort_values("alpha")
    ax.plot(subset["alpha"], subset["test_r2"], marker="o", label=name)
ax.axhline(ols_scaled_r2 := test_metrics["r2"], color="grey", linestyle="--",
           label=f"OLS (test R\\u00b2={test_metrics['r2']:.3f})")
ax.set_xscale("log")
ax.set_xlabel("alpha (regularisation strength, log scale)")
ax.set_ylabel("Test R\\u00b2")
ax.set_title("Effect of regularisation strength on test R\\u00b2")
ax.legend()
plt.tight_layout()
plt.savefig("../figures/06_regularisation.png", bbox_inches="tight")
plt.show()
"""
)

md(
    """
### Regression metrics summary (all models)

A single table comparing OLS, the best Ridge, and the best Lasso on the test set.
"""
)

code(
    """
# Re-train one representative Ridge and Lasso (best alpha by test R2) for a clean summary.
best_ridge_alpha = results_df[results_df["model"] == "Ridge"].iloc[0]["alpha"]
best_lasso_alpha = results_df[results_df["model"] == "Lasso"].iloc[0]["alpha"]

summary = {
    "OLS":          (test_metrics["r2"], test_metrics["rmse"]),
    "Ridge (best)": (results_df[results_df["model"] == "Ridge"].iloc[0]["test_r2"],
                     results_df[results_df["model"] == "Ridge"].iloc[0]["test_rmse"]),
    "Lasso (best)": (results_df[results_df["model"] == "Lasso"].iloc[0]["test_r2"],
                     results_df[results_df["model"] == "Lasso"].iloc[0]["test_rmse"]),
}
summary_df = pd.DataFrame(summary, index=["Test R2", "Test RMSE"]).T
print(summary_df.to_string(
    formatters={"Test R2": "{:.4f}".format, "Test RMSE": "{:,.0f}".format}
))
"""
)

md(
    """
**Takeaway.** On this data the models land very close together: linear regression already
captures most of the signal, and regularisation mainly guards against unstable coefficients
without a large change in test R². Lasso's `n_nonzero_coefs` column shows how aggressively it
prunes features — useful when you have hundreds of candidate predictors (as in the real Ames
dataset with ~80 features).
"""
)

# ======================================================================
md(
    """
## 12. Conclusions & next steps

**What we did**
- Loaded and explored the data; found and quantified missing values in `area`, `bathrooms`,
  `garage`, `age`.
- Reasoned about feature relevance before modelling, then validated it with a correlation
  heatmap.
- Imputed missing values (median) and One-Hot Encoded `location` (dummy-variable-trap safe).
- Split 80/20, trained OLS Linear Regression, and evaluated with MSE, RMSE, MAE, and R² on both
  splits.
- Diagnosed the model with an actual-vs-predicted scatter and a residual plot.
- Interpreted coefficients (raw + standardised) to rank feature impact.
- Compared against Ridge and Lasso across a range of penalty strengths.

**Key findings**
- `area` and `quality` are the dominant positive drivers; `age` is the main negative one.
- Location dummies carry large effects — location is a first-class price driver.
- Train/test R² are close, so the linear model generalises rather than overfits.
- Regularisation (Ridge/Lasso) yields comparable accuracy while stabilising coefficients and,
  for Lasso, pruning unnecessary features.

**Honest limitations & next steps**
- Linear regression assumes additive, linear effects. Real prices have **interactions**
  (e.g. area × location) and non-linearities (age vs price is U-shaped for some markets).
- The target is mildly skewed; training on `log(price)` often improves residual normality and
  handles the high-price tail better.
- Multicollinearity between `area` and `rooms` muddies individual coefficients — Ridge helps.
- For the real Ames / Kaggle dataset, swap the CSV path and this same pipeline applies, with
  extra work to encode ~40 categorical columns and handle the many NA-as-a-category fields.
- Worth trying next: `PolynomialFeatures` for interactions, `GridSearchCV` to tune alpha
  properly (with cross-validation), and gradient-boosted trees as a strong non-linear baseline.
"""
)

nb["cells"] = cells
nb["metadata"] = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python"},
}

import os

os.makedirs("notebooks", exist_ok=True)
out_path = "notebooks/house_price_linear_regression.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    nbf.write(nb, f)
print(f"Wrote {out_path} with {len(cells)} cells")
